version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: therapist-db
    environment:
      - ORACLE_PWD=${ORACLE_PASSWORD:-YourSecurePassword123!}
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./database:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/${ORACLE_PASSWORD:-YourSecurePassword123!}@//localhost:1521/FREEPDB1 | grep -q '^1'"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: therapist-backend
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_HOST=oracle-db
      - DATABASE_PORT=1521
    ports:
      - "8000:8000"
    depends_on:
      oracle-db:
        condition: service_healthy
    volumes:
      - ${HOME}/.oci:/app/.oci:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: therapist-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  oracle-data:
    driver: local

networks:
  default:
    name: therapist-network
