-- Therapist Office Application Database Schema
-- Oracle Database 23ai
-- Run as: therapist_app user

-- Drop tables if they exist (for clean install)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE access_audit_log CASCADE CONSTRAINTS';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE evidence_base_documents CASCADE CONSTRAINTS';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE treatment_templates CASCADE CONSTRAINTS';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE treatment_plans CASCADE CONSTRAINTS';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE session_notes CASCADE CONSTRAINTS';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE patients CASCADE CONSTRAINTS';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE therapists CASCADE CONSTRAINTS';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Therapists Table
CREATE TABLE therapists (
    therapist_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    license_number VARCHAR2(50),
    password_hash VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP,
    is_active NUMBER(1) DEFAULT 1,
    CONSTRAINT chk_email_format CHECK (REGEXP_LIKE(email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'))
);

-- Patients Table
CREATE TABLE patients (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    therapist_id NUMBER NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    date_of_birth DATE,
    patient_category VARCHAR2(100),
    initial_assessment_date DATE,
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_patient_therapist FOREIGN KEY (therapist_id) 
        REFERENCES therapists(therapist_id),
    CONSTRAINT chk_patient_status CHECK (status IN ('ACTIVE', 'DISCHARGED', 'ON_HOLD'))
);

-- Session Notes Table
CREATE TABLE session_notes (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    therapist_id NUMBER NOT NULL,
    session_number NUMBER,
    session_date DATE NOT NULL,
    session_duration_minutes NUMBER,
    presenting_concerns CLOB,
    symptoms_observed CLOB,
    clinical_observations CLOB,
    interventions_used CLOB,
    patient_response CLOB,
    risk_assessment CLOB,
    homework_assigned CLOB,
    session_summary CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_session_patient FOREIGN KEY (patient_id) 
        REFERENCES patients(patient_id),
    CONSTRAINT fk_session_therapist FOREIGN KEY (therapist_id) 
        REFERENCES therapists(therapist_id)
);

-- Treatment Plans Table
CREATE TABLE treatment_plans (
    plan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    therapist_id NUMBER NOT NULL,
    plan_version NUMBER DEFAULT 1,
    diagnosis_codes VARCHAR2(500),
    dsm_diagnosis VARCHAR2(500),
    treatment_goals CLOB,
    recommended_interventions CLOB,
    treatment_modality VARCHAR2(100),
    session_frequency VARCHAR2(50),
    estimated_duration VARCHAR2(50),
    ai_generated_recommendations CLOB,
    therapist_notes CLOB,
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    start_date DATE,
    review_date DATE,
    end_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_plan_patient FOREIGN KEY (patient_id) 
        REFERENCES patients(patient_id),
    CONSTRAINT fk_plan_therapist FOREIGN KEY (therapist_id) 
        REFERENCES therapists(therapist_id),
    CONSTRAINT chk_plan_status CHECK (status IN ('DRAFT', 'ACTIVE', 'COMPLETED', 'DISCONTINUED'))
);

-- Treatment Templates Table
CREATE TABLE treatment_templates (
    template_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name VARCHAR2(200) NOT NULL,
    patient_category VARCHAR2(100) NOT NULL,
    diagnosis_category VARCHAR2(200),
    evidence_based_interventions CLOB,
    typical_treatment_modalities VARCHAR2(500),
    recommended_goals CLOB,
    session_structure CLOB,
    success_indicators CLOB,
    references CLOB,
    created_by_therapist_id NUMBER,
    is_office_wide NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_template_therapist FOREIGN KEY (created_by_therapist_id) 
        REFERENCES therapists(therapist_id)
);

-- Evidence Base Documents (for RAG)
CREATE TABLE evidence_base_documents (
    document_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR2(50),
    category VARCHAR2(100),
    title VARCHAR2(500) NOT NULL,
    content CLOB NOT NULL,
    source VARCHAR2(500),
    publication_date DATE,
    embedding VECTOR(1024, FLOAT32),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- Audit Log Table
CREATE TABLE access_audit_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    therapist_id NUMBER NOT NULL,
    action VARCHAR2(100) NOT NULL,
    resource_type VARCHAR2(50) NOT NULL,
    resource_id NUMBER,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_therapist FOREIGN KEY (therapist_id) 
        REFERENCES therapists(therapist_id)
);

-- Create indexes for performance
CREATE INDEX idx_patients_therapist ON patients(therapist_id);
CREATE INDEX idx_patients_status ON patients(status);
CREATE INDEX idx_sessions_patient ON session_notes(patient_id);
CREATE INDEX idx_sessions_therapist ON session_notes(therapist_id);
CREATE INDEX idx_sessions_date ON session_notes(session_date);
CREATE INDEX idx_plans_patient ON treatment_plans(patient_id);
CREATE INDEX idx_plans_therapist ON treatment_plans(therapist_id);
CREATE INDEX idx_plans_status ON treatment_plans(status);
CREATE INDEX idx_templates_category ON treatment_templates(patient_category);
CREATE INDEX idx_evidence_category ON evidence_base_documents(category);
CREATE INDEX idx_audit_therapist ON access_audit_log(therapist_id);
CREATE INDEX idx_audit_timestamp ON access_audit_log(timestamp);

-- Create vector index on evidence documents (only if vector memory is configured)
BEGIN
    EXECUTE IMMEDIATE 'CREATE VECTOR INDEX idx_evidence_embedding ON evidence_base_documents(embedding) 
        ORGANIZATION NEIGHBOR PARTITIONS 
        DISTANCE COSINE 
        WITH TARGET ACCURACY 95';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Note: Vector index creation skipped. Ensure vector_memory_size is configured.');
        DBMS_OUTPUT.PUT_LINE('Run: ALTER SYSTEM SET vector_memory_size=500M SCOPE=SPFILE; then restart database.');
END;
/

-- Insert sample data (optional)
-- Sample therapist
INSERT INTO therapists (email, first_name, last_name, license_number, password_hash, is_active)
VALUES ('demo@therapist.com', 'Demo', 'Therapist', 'LIC12345', '$2b$12$dummy_hash_replace_in_production', 1);

-- Sample treatment template
INSERT INTO treatment_templates (
    template_name, 
    patient_category, 
    diagnosis_category,
    evidence_based_interventions,
    typical_treatment_modalities,
    recommended_goals,
    session_structure,
    success_indicators,
    references,
    created_by_therapist_id,
    is_office_wide
) VALUES (
    'Anxiety Disorders - CBT Protocol',
    'Anxiety',
    'Generalized Anxiety Disorder',
    'Cognitive Behavioral Therapy (CBT), Exposure Therapy, Relaxation Training, Cognitive Restructuring',
    'Individual CBT, Group Therapy',
    '1. Reduce anxiety symptoms by 50% as measured by GAD-7
2. Develop 3 effective coping strategies
3. Improve daily functioning and quality of life
4. Reduce avoidance behaviors',
    'Session 1-2: Assessment and psychoeducation
Sessions 3-6: Cognitive restructuring
Sessions 7-12: Exposure therapy
Sessions 13-16: Relapse prevention',
    '- GAD-7 score reduction
- Increased engagement in previously avoided activities
- Improved sleep quality
- Self-reported anxiety reduction',
    'APA Clinical Practice Guideline for Anxiety Disorders (2020)
Barlow, D.H. (2021). Clinical Handbook of Psychological Disorders',
    1,
    1
);

COMMIT;

-- Display created tables
SELECT table_name FROM user_tables ORDER BY table_name;

-- Display row counts
SELECT 'therapists' as table_name, COUNT(*) as row_count FROM therapists
UNION ALL
SELECT 'treatment_templates', COUNT(*) FROM treatment_templates;
